# Configure your logstash host here
# See complete.toml to write to Elastic directly and/or to a file
# [logstash]
# host = "localhost:8888"

# [filesink]
# retain_hours = 1 

[app]
# workers = 1 # max number of concurrent workers.  Defaults to the number of cores
summary = true # prints a summary of events to stdout after running
samples = true # prints one of each type event to samples.xe.json after running

[defaults]
sessions = ["system_health"]
look_back = "168h" # one week
rows = 10   # 20000 is a good value.  Lots of events but doesn't block too long.  0 or omitted processes all the rows

timestamp_field_name = "@timestamp"
payload_field_name = "mssql" # all the XE events are under this field

exclude_17830 = true
excludedEvents = [
    "connectivity_ring_buffer_recorded",
    "memory_broker_ring_buffer_recorded",
    "scheduler_monitor_system_health_ring_buffer_recorded",
    "security_error_ring_buffer_recorded"
    ]

[[source]]
fqdn = "localhost"


